const fruits = [
  {
    id: 1,
    name: 'Apple',
    category: 'Fruit',
    image: 'https://tse2.mm.bing.net/th?id=OIP.5bLEGgrUJw9PXpPA3ReYBwHaGU&pid=Api&P=0',
    price: 100,
    benefits: 'Rich in antioxidants and dietary fiber, promotes heart health',
    unit: 'KG',
  },

  
  {
    id: 3,
    name: 'Orange',
    category: 'Fruit',
    image: 'https://tse2.mm.bing.net/th?id=OIP.cHoLk438U6MMz_b3IRKTgQHaE2&pid=Api&P=0',
    price: 80,
    benefits: 'Rich in vitamin C, boosts immunity, promotes skin health',
  },
  {
    id: 4,
    name: 'Mango',
    category: 'Fruit',
    image: 'https://tse1.mm.bing.net/th?id=OIP.LJJ0uDYS5ZhDr2zJA-Q9sAHaFe&pid=Api&P=0',
    price: 120,
    benefits: 'Rich in vitamins A and C, promotes eye health, boosts immunity',
  },
  {
    id: 5,
    name: 'Pineapple',
    category: 'Fruit',
    image: 'https://tse1.mm.bing.net/th?id=OIP.o0JSExiLmf62YcdwxXlR3QHaHa&pid=Api&P=0',
    price: 90,
    benefits: 'Rich in vitamin C and antioxidants, aids digestion, reduces inflammation',
  },
  {
    id: 6,
    name: 'Watermelon',
    category: 'Fruit',
    image: 'https://tse3.mm.bing.net/th?id=OIP.h9K4jbifMUHS1L_Um2xfuQHaF3&pid=Api&P=0&h=180',
    price: 70,
    benefits: 'Rich in vitamins A and C, promotes hydration, aids digestion',
  },
  {
    id: 7,
    name: 'Grapes',
    category: 'Fruit',
    image: 'https://tse2.mm.bing.net/th?id=OIP.yOkQl1kiITBJA0oUopHq3AHaE8&pid=Api&P=0&h=180',
    price: 60,
    benefits: 'Rich in antioxidants, promotes heart health, reduces inflammation',
  },
  {
    id: 8,
    name: 'Strawberry',
    category: 'Fruit',
    image: 'https://tse4.mm.bing.net/th?id=OIP.tpcWNqSwdYtqRzlbG6bF3QHaFF&pid=Api&P=0&h=180',
    price: 110,
    benefits: 'Rich in vitamin C and antioxidants, promotes skin health, reduces inflammation',
  },
  {
    id: 9,
    name: 'Pomegranate',
    category: 'Fruit',
    image: 'https://tse3.mm.bing.net/th?id=OIP.6p0Ki5llNvIDDFRIVU5HSwHaFj&pid=Api&P=0&h=180',
    price: 130,
    benefits: 'Rich in antioxidants, promotes heart health, reduces inflammation',
  },
  {
    id: 10,
    name: 'Blueberry',
    category: 'Fruit',
    image: 'https://tse3.mm.bing.net/th?id=OIP.9KLs1VGtBweKVLJeX2y6vgHaHB&pid=Api&P=0&h=180',
    price: 95,
    benefits: 'Rich in antioxidants and dietary fiber, promotes brain health, reduces inflammation',
  },
  {
    id: 11,
    name: 'Avocado',
    category: 'Fruit',
    image: 'https://tse2.mm.bing.net/th?id=OIP.JnCMm3camJzDF7sU8JYz4gHaFH&pid=Api&P=0&h=180',
    price: 150,
    benefits: 'Rich in healthy fats, promotes heart health, aids digestion',
  },
  {
    id: 12,
    name: 'Kiwi',
    category: 'Fruit',
    image: 'https://tse3.mm.bing.net/th?id=OIP.h3eda6g4hG65tBvLwTHR2QHaF5&pid=Api&P=0',
    price: 85,
    benefits: 'Rich in vitamin C and antioxidants, promotes digestion, boosts immunity',
  },
  {
    id: 13,
    name: 'Pear',
    category: 'Fruit',
    image: 'https://tse3.mm.bing.net/th?id=OIP.3aTLaPO8nmqVihDswWej5gHaE_&pid=Api&P=0&h=180',
    price: 75,
    benefits: 'Rich in dietary fiber, promotes heart health, aids digestion',
  },
  {
    id: 14,
    name: 'Dragon fruit',
    category: 'Fruit',
    image: 'https://tse2.mm.bing.net/th?id=OIP.LY7wv_BP7c9z7by_-FdXaQHaEt&pid=Api&P=0&h=180',
    price: 200,
    benefits: 'Rich in vitamin C and antioxidants, promotes digestion, boosts immunity',
  },
  {
    id: 15,
    name: 'Lemon',
    category: 'Fruit',
    image: 'https://tse4.mm.bing.net/th?id=OIP.WPtGAC9rbhE2-ltmfRJXRQHaHa&pid=Api&P=0&h=180',
    price: 30,
    benefits: 'Rich in vitamin C and antioxidants, promotes digestion, boosts immunity',
  },
  {
    id: 16,
    name: 'Raspberry',
    category: 'Fruit',
    image: 'https://tse3.mm.bing.net/th?id=OIP.ZOn8HQUqEVUwaUdg_PGa2AHaGD&pid=Api&P=0&h=180',
    price: 120,
    benefits: 'Rich in vitamin C and antioxidants, promotes skin health, reduces inflammation',
  },
  {
    id: 17,
    name: 'Cherry',
    category: 'Fruit',
    image: 'https://tse4.mm.bing.net/th?id=OIP.BYppNGMX8lZ1BzjsY8eluAHaFO&pid=Api&P=0&h=180',
    price: 100,
    benefits: 'Rich in antioxidants, promotes heart health, reduces inflammation',
  },
  {
    id: 18,
    name: 'Grapefruit',
    category: 'Fruit',
    image: 'https://tse1.mm.bing.net/th?id=OIP.mxTWaInuLkGzskvQBg-TMAHaHa&pid=Api&P=0&h=180',
    price: 65,
    benefits: 'Rich in vitamin C and antioxidants, promotes weight loss, boosts immunity',
  },
  {
    id: 19,
    name: 'Cantaloupe',
    category: 'Fruit',
    image: 'https://tse4.mm.bing.net/th?id=OIP.jS12ohd13e3jxPUX150soAHaHa&pid=Api&P=0&h=180',
    price: 80,
    benefits: 'Rich in vitamins A and C, promotes hydration, aids digestion',
  },
  {
    id: 20,
    name: 'Plum',
    category: 'Vegetable',
    image: 'https://tse2.mm.bing.net/th?id=OIP.OQindMby5rwzp3hCHZV02QHaEK&pid=Api&P=0&h=180',
    price: 90,
    benefits: 'Rich in dietary fiber, promotes digestion, reduces inflammation',
  },
  {
    id: 21,
    name: 'Carrot',
    category: 'Vegetable',
    image: 'https://tse4.mm.bing.net/th?id=OIP.3EL9HFK5Ic0DjCqOC1peywHaD-&pid=Api&P=0&h=180',
    price: 1.99,
    benefits: 'Rich in beta-carotene, promotes healthy vision, boosts immune system',
  },
  {
    id: 22,
    name: 'Broccoli',
    category: 'Vegetable',
    image: 'https://tse4.mm.bing.net/th?id=OIP.z6W694qvtJZbZzQ6NC_C_QHaHI&pid=Api&P=0&h=180',
    price: 2.49,
    benefits: 'High in fiber, vitamins, and minerals, supports digestion, strengthens bones',
  },
  {
    id: 23,
    name: 'Spinach',
    category: 'Leafy',
    image: 'https://tse2.mm.bing.net/th?id=OIP.vPJaRl4r6AfFCivfMT2qVAHaFy&pid=Api&P=0&h=180',
    price: 1.79,
    benefits: 'Packed with iron and antioxidants, promotes healthy skin, supports brain health',
  },
  // Add more vegetables here following the same format
  {
    id: 38,
    name: 'Zucchini',
    category: 'Vegetable',
    image: 'https://tse2.mm.bing.net/th?id=OIP.lodwSZo3EjRAtvDCINAPowHaFJ&pid=Api&P=0&h=180',
    price: 1.49,
    benefits: 'Low in calories, aids digestion, supports healthy metabolism',
  },
  {
    id: 39,
    name: 'Eggplant',
    category: 'Vegetable',
    image: 'https://tse2.mm.bing.net/th?id=OIP.yh3D9-kMQW7a5VQ110VHXAHaHa&pid=Api&P=0&h=180',
    price: 1.99,
    benefits: 'High in antioxidants, supports heart health, aids in weight management',
  },
  {
    id: 40,
    name: 'Sweet Potato',
    category: 'Vegetable',
    image: 'https://tse1.mm.bing.net/th?id=OIP.LW0xLQckse5pfdR2UCcVuQHaHa&pid=Api&P=0&h=180',
    price: 1.99,
    benefits: 'Rich in beta-carotene, supports eye health, boosts immune system',
  },
  {
    id: 41,
    name: 'Cabbage',
    category: 'Vegetable',
    image: 'https://tse1.mm.bing.net/th?id=OIP.iN_5_oDOnEzI-RhAN5XmcgHaHa&pid=Api&P=0&h=180',
    price: 1.59,
    benefits: 'High in vitamins K and C, aids digestion, supports a healthy gut',
  },
  {
    id: 42,
    name: 'Asparagus',
    category: 'Vegetable',
    image: 'https://tse3.mm.bing.net/th?id=OIP._F2n_hJ9Vw6DN7R4qqz8UwHaGc&pid=Api&P=0&h=180',
    price: 2.49,
    benefits: 'Detoxifying properties, supports healthy liver function, aids in weight loss',
  },
  {
    id: 43,
    name: 'Green Beans',
    category: 'Vegetable',
    image: 'https://tse2.mm.bing.net/th?id=OIP.FLyEUPcpg_JzQDPPLZg6VAAAAA&pid=Api&P=0&h=180',
    price: 1.79,
    benefits: 'Low in calories, high in vitamins and minerals, supports healthy digestion',
  },


    {
      id: 45,
      name: 'Kale /केल',
      category: 'Leafy',
      image: 'https://tse2.mm.bing.net/th?id=OIP.7VS9NaOuqrvjERzj0_gC4AHaEs&pid=Api&P=0&h=180',
      price: 2.99,
      benefits: 'Rich in vitamins A, C, and K, high in fiber',
    },
    {
      id: 46,
      name: 'Arugula / अरुगुला',
      category: 'Leafy',
      image: 'https://tse3.mm.bing.net/th?id=OIP.Un3FpR7h6cz2ojzPxcwreAHaE7&pid=Api&P=0&h=180',
      price: 2.49,
      benefits: 'Peppery taste, good source of folate and vitamins A, C, and K',
    },
    {
      id: 47,
      name: 'Romaine Lettuce / रोमेन लेटस',
      category: 'Leafy',
      image: 'https://tse2.mm.bing.net/th?id=OIP.-hz-zDtmLN6hS0WFMunjqgHaHa&pid=Api&P=0&h=180',
      price: 1.99,
      benefits: 'Crisp texture, high in vitamins A and K',
    },
    {
      id: 48,
      name: 'Swiss Chard / स्विस चार्ड',
      category: 'Leafy',
      image: 'https://tse2.mm.bing.net/th?id=OIP.3XO3Nase0YxJVsAQHqafuQHaI3&pid=Api&P=0&h=180',
      price: 2.79,
      benefits: 'Colorful stems, rich in vitamins A, C, and K',
    },
    {
      id: 49,
      name: 'Collard Greens / कोलार्ड ग्रीन्स',
      category: 'Leafy',
      image: 'https://tse2.mm.bing.net/th?id=OIP.qGYQqiwddxHA3QmVVRM67AHaEA&pid=Api&P=0&h=180',
      price: 1.89,
      benefits: 'Nutritious, high in vitamins A, C, and K',
    },
    {
      id: 50,
      name: 'Watercress / वाटरक्रेस',
      category: 'Leafy',
      image: 'https://tse1.mm.bing.net/th?id=OIP.n_-pHczE4QlzIlic0ZVIwgHaDt&pid=Api&P=0&h=180',
      price: 2.29,
      benefits: 'Peppery taste, rich in vitamins A, C, and K',
    },
    {
      id: 51,
      name: 'Mustard Greens / तोरीको साग',
      category: 'Leafy',
      image: 'https://tse2.mm.bing.net/th?id=OIP.EGKPs3f_fliMYTpnT9Z86wHaE8&pid=Api&P=0&h=180',
      price: 1.79,
      benefits: 'Peppery taste, high in vitamins A, C, and K',
    },
    {
      id: 52,
      name: 'Bok Choy / चाइनिज पाल्क',
      category: 'Leafy',
      image: 'https://tse4.mm.bing.net/th?id=OIP.1b8eFQ-9c8uJ8_B1nbYAuAHaFe&pid=Api&P=0&h=180',
      price: 2.39,
      benefits: 'Crunchy texture, rich in vitamins A and C',
    },

 
      {
        id: 54,
        name: 'Aama ko Achar',
        category: 'Pickle',
        image: 'https://tse4.mm.bing.net/th?id=OIP.bb2UMxqQveSiqWRLDXhXcAHaHa&pid=Api&P=0&h=180',
        price: 100,
        benefits: 'Rich in antioxidants and dietary fiber, promotes heart health',
        viewedproducts: 'yes',
        unit: 'BOTTLE',
      },
      {
        id: 55,
        name: 'Mango Pickle',
        category: 'Pickle',
        image: 'https://tse4.mm.bing.net/th?id=OIP.T9qwDX1ZETVSiAOqD2m5vgHaIt&pid=Api&P=0&h=180',
        price: 120,
        benefits: 'Made with fresh mangoes, enhances the taste of meals',
        viewedproducts: 'no',
        unit: 'BOTTLE',
      },
      {
        id: 56,
        name: 'Lime Pickle',
        category: 'Pickle',
        image: 'https://tse2.mm.bing.net/th?id=OIP.-dCzDdXiTVHdkrS4RMDFLwHaHa&pid=Api&P=0&h=180',
        price: 90,
        benefits: 'Tangy and flavorful, adds zest to dishes',
        viewedproducts: 'yes',
        unit: 'BOTTLE',
      },
      {
        id: 57,
        name: 'Mixed Vegetable Pickle',
        category: 'Pickle',
        image: 'https://tse4.mm.bing.net/th?id=OIP.dgx_J7xUvdbOZehVtCw82QHaHa&pid=Api&P=0&h=180',
        price: 150,
        benefits: 'Blend of various vegetables, offers a medley of flavors',
        viewedproducts: 'yes',
        unit: 'BOTTLE',
      },
      {
        id: 58,
        name: 'Chili Pickle',
        category: 'Pickle',
        image: 'https://tse3.mm.bing.net/th?id=OIP.hARiu9Jtij_BgFkcP9FDdwHaHZ&pid=Api&P=0&h=180',
        price: 80,
        benefits: 'Spicy and hot, adds a kick to meals',
        viewedproducts: 'no',
        unit: 'BOTTLE',
      },
      {
        id: 59,
        name: 'Garlic Pickle',
        category: 'Pickle',
        image: 'https://tse4.mm.bing.net/th?id=OIP.aCS_Mjz6jr24sE7KI7xt2QHaIU&pid=Api&P=0&h=180',
        price: 110,
        benefits: 'Strong and aromatic, enhances the taste of dishes',
        viewedproducts: 'yes',
        unit: 'BOTTLE',
      },
      {
        id: 60,
        name: 'Mango-Ginger Pickle',
        category: 'Pickle',
        image: 'https://tse4.mm.bing.net/th?id=OIP.t881goG-PrIuXNDzqyjDFQHaIq&pid=Api&P=0&h=180',
        price: 130,
        benefits: 'Combines the flavors of mangoes and ginger, tangy and refreshing',
        viewedproducts: 'no',
        unit: 'BOTTLE',
      },
      {
        id: 61,
        name: 'Carrot Pickle',
        category: 'Pickle',
        image: 'https://tse4.mm.bing.net/th?id=OIP.c3m5tgiiGjBewz4nHN19fwHaHa&pid=Api&P=0&h=180',
        price: 95,
        benefits: 'Crunchy and tangy, adds a vibrant touch to meals',
        viewedproducts: 'yes',
        unit: 'BOTTLE',
      },
      {
        id: 62,
        name: 'Green Chili Pickle',
        category: 'Pickle',
        image: 'https://tse4.mm.bing.net/th?id=OIP.hYRHMq_583uEWRfxEvXnPwHaHa&pid=Api&P=0&h=180',
        price: 85,
        benefits: 'Fiery and flavorful, pairs well with a variety of dishes',
        viewedproducts: 'no',
        unit: 'BOTTLE',
      },
      {
        id: 63,
        name: 'Cauliflower Pickle',
        category: 'Pickle',
        image: 'https://tse1.mm.bing.net/th?id=OIP.wFkUibXhQch7Xun8qRFhegHaE7&pid=Api&P=0&h=180',
        price: 105,
        benefits: 'Delicious and tangy, a unique twist to pickle varieties',
        viewedproducts: 'yes',
        unit: 'BOTTLE',
      }

    
  
  
];

  export default fruits;